$('#Start').click(
    function(){
        $('#screenTitle').hide();
    }
)
$('#close').click(
    function(){
        $('#InstructionContent').hide();
    }
)
$('#Instruction').click(
    function(){
        $('#InstructionContent').show();
    }
)